version: '3.5'
  
services:
  mysql1:
    image: mysql:latest
    container_name: mysql1
    environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: pucsd
        MYSQL_DB: pucsd
    ports: ["3307:3306"]
    restart: always

  mysql2:
    image: mysql:latest
    container_name: mysql2
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: pucsd
       MYSQL_DB: pucsd
    ports: ["3308:3306"]
    restart: always

  mysql3:
    image: mysql:latest
    container_name: mysql3
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: pucsd
       MYSQL_DB: pucsd
    ports: ["3309:3306"]
    restart: always
